### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by myusrn** [cweijan/vscode-database-client#110] opened 2021-01-27 02:33 UTC
- OS INFO : windows 20h2 19042.746

Where is this "Show Total on result view" supposed to be displayed in results pane?  I'm expecting a count of rows returned like you get in mysql workbench but i'm apparently overlooking where it is surfaced.

![image](https://user-images.githubusercontent.com/3043446/105934179-86a49200-6004-11eb-84f9-6f632a9caa10.png)

![image](https://user-images.githubusercontent.com/3043446/105934330-d5eac280-6004-11eb-9775-30cca8de535e.png)

![image](https://user-images.githubusercontent.com/3043446/105934335-d7b48600-6004-11eb-813a-d69e3a0db084.png)

**Comment by cweijan** [comment] 2021-01-27 03:17
It only shows when you look up the table.
![image](https://user-images.githubusercontent.com/27798227/105937776-31629200-6091-11eb-8ee8-7f3694c680f6.png)

**Comment by cweijan** [comment] 2021-01-27 03:18
I haven't used workbench, then this extension doesn't follow the behavior of workbench.

**Comment by myusrn** [comment] 2021-01-27 04:25
Thanks for the followup on this request.  

In your screen grab i'm seeing "100/page" and "go to 1" is that what you mean is enabled by the extension setting "Show Total on result view", in other words it displays how many pages there are in the result set?  

When i turn off that extension setting i still see the "100/page" and "go to 1" UI elements in the result view.  

What i was hoping for is a default behavior, or an extension setting controlled behavior, that causes how many rows are in the result set of the sql statement that was executed to be displayed.  This saves users from having to change "select * from . . . " to "select count(*) from . . . " every time you want to determine how many rows are in the result set.

For example something like this . . . 

![image](https://user-images.githubusercontent.com/3043446/105943324-e48da580-6015-11eb-9c4d-c0e03d435387.png)

**Comment by cweijan** [comment] 2021-01-27 04:50
![image](https://user-images.githubusercontent.com/27798227/105944388-311cc380-609e-11eb-9c7f-e0cd2e4fe8b4.png)

**Comment by cweijan** [comment] 2021-01-27 05:41
Only one table support show count.

**Comment by cweijan** [comment] 2021-01-27 07:53
Only a single table will be automatically counted. This is not a bug, so I close the issue .

**Closed as completed by cweijan** 2021-01-27 07:53 UTC
Labels: bug
